version: "3.7"
services:
  train:
    image: service/serve:${MODEL_VERSION}
    build:
      context: .
      dockerfile: service/serve/Dockerfile
      args:
        - MODEL_VERSION=${MODEL_VERSION}
        - RUN_TESTS=n
    volumes:
      - ${PWD}/../data:/data
      - ${PWD}/../model:/model