version: "3.7"
services:
  train:
    image: service/train:${MODEL_VERSION}
    build:
      context: .
      dockerfile: service/train/Dockerfile
      args:
        - MODEL_VERSION=${MODEL_VERSION}
        - RUN_TESTS=n
    volumes:
      - ../data/UD_English-GUM:/data
      - ../model:/model