version: "3.7"
services:
  train:
    image: service/train:${MODEL_VER}
    build:
      context: .
      dockerfile: service/train/Dockerfile
      args:
        - MODEL_VERSION=${MODEL_VER}
    volumes:
      - type: bind
        source: ${BUCKET_DATA}
        target: /data
      - type: bind
        source: ${BUCKET_MODEL}
        target: /model