version: "3.7"
services:
  train:
    image: service/train:${MODEL_VER}
    build:
      context: .
      dockerfile: service/train/Dockerfile
      args:
        - MODEL_VERSION=${MODEL_VER}
    volumes:
      - ${PWD}/../data:/data
      - ${PWD}/../model:/model