version: "3.7"
services:
  serve:
    image: service/serve:${MODEL_VERSION}
    build:
      context: .
      dockerfile: service/serve/Dockerfile
      args:
        - MODEL_VERSION=${MODEL_VERSION}
        - RUN_TESTS=n
    volumes:
      - ../data:/data
      - ../model:/model
    environment:
      - BUCKET_DATA_INPUT=/data/prediction/input
      - BUCKET_DATA_OUTPUT=/data/prediction/output
      - BUCKET_MODEL=/model